name: Alexa Shopping List Sync Fixed
version: "2410.276b"
slug: fixed_addon
description: Alexa Shopping List synchronisation server fixed
url: "https://github.com/matte-oss/alexa-shopping-list-fix"
arch:
  - aarch64
  - amd64
image: "aronnebrivio/ha-alexa-shopping-list-sync"
startup: "services"
ports:
  4000/tcp: 4000
map:
  - type: data
    path: "/config"
    read_only: false
