name: Alexa Shopping List Sync Fixed
version: "2410.276"
slug: fixed_addon
description: Alexa Shopping List synchronisation server fixed
url: "https://github.com/madmachinations/home-assistant-alexa-shopping-list"
arch:
  - aarch64
  - amd64
image: "madmachinations/ha-alexa-shopping-list-sync"
startup: "services"
ports:
  4000/tcp: 4000
map:
  - type: data
    path: "/config"
    read_only: false
